export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Ayush",
  description: "I'm a software engineer with a passion for building scalable and efficient systems.",
  links: {
    caldotcom: "https://cal.com/ayush-kumar-anand/30min",
    github: "https://github.com/ayushk-1801",
    twitter: "https://x.com/ayushk1801",
    linkedin: "https://linkedin.com/in/ayush-kumar-anand",
    email: "ayushkumar.swe@gmail.com",
    resume: "/resume.pdf"
  },
  techStack: [
    { name: "javascript", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" },
    { name: "typescript", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/typescript/typescript-original.svg" },
    { name: "rust", src: "/rust.svg" },
    { name: "react", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg" },
    { name: "nextjs", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original.svg" },
    { name: "turborepo", src: "/turborepo.svg" },
    { name: "html5", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg" },
    { name: "css3", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg" },
    { name: "tailwindcss", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/tailwindcss/tailwindcss-original.svg" },
    { name: "nodejs", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg" },
    { name: "express", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original.svg" },
    { name: "git", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/git/git-original.svg" },
    { name: "github", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/github/github-original.svg" },
    { name: "zustand", src: "/zustand.svg" },
    { name: "mongodb", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original.svg" },
    { name: "postgresql", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original.svg" },
    { name: "drizzle", src: "/drizzle.svg" },
    { name: "prisma", src: "https://raw.githubusercontent.com/prisma/presskit/main/Assets/Prisma-DarkSymbol.svg" },
    { name: "better-auth", src: "/better-auth.svg" },
    { name: "docker", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original.svg" },
    { name: "supabase", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/supabase/supabase-original.svg" },
    { name: "redis", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/redis/redis-original.svg"},
    { name: "electron", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg" },
    { name: "python", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg" },
    { name: "c", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg" },
    { name: "cpp", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg" },
  ],
  experiences: [
    {
      company: "AIPHI AI",
      logo: "/aiphiai.svg",
      position: "Full Stack AI Engineer Intern",
      from: "May 2025",
      to: "Present",
      description: "",
      website: "https://aiphi.ai/"
    },
    {
      company: "Audient",
      logo: "/audient.svg",
      position: "Full Stack Developer",
      from: "Jan 2025",
      to: "Apr 2025",
      description: "Built a high-performance event booking platform for live shows, boosting audience engagement by 60%. Developed an admin dashboard to streamline event management and optimized site performance for faster load times and improved SEO.",
      website: "https://audient.in/"
    }
  ],
  projects: [
    {
      name: "Benkyoshi",
      description: "Benkyoshi transforms YouTube playlists into structured, distraction-free learning experiences with AI-enhanced features. It offers automated course creation, intelligent notes and quizzes, progress tracking, and personalized learning.",
      date: "April 2025",
      techStack: [
        { name: "nextjs", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original.svg" },
        { name: "typescript", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/typescript/typescript-original.svg" },
        { name: "tailwindcss", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/tailwindcss/tailwindcss-original.svg" },
        { name: "drizzle", src: "/drizzle.svg" },
        { name: "postgresql", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original.svg" },
        { name: "zustand", src: "/zustand.svg" },
        { name: "gemini", src: "/gemini.svg" },
      ],
      liveLink: "https://benkyoshi.vercel.app/",
      githubLink: "https://github.com/ayushk-1801/gdg-hackathon",
      videoLink: "/benkyoshi.mp4",
    },
    {
      name: "Audient",
      description: "It is a platform that lets users discover and book exclusive tickets for live comedy, music, and poetry events. It offers a seamless and secure booking experience, access to unique performances, and a curated selection of top-tier entertainment for unforgettable moments.",
      date: "March 2025",
      techStack: [
        { name: "nextjs", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original.svg" },
        { name: "typescript", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/typescript/typescript-original.svg" },
        { name: "tailwindcss", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/tailwindcss/tailwindcss-original.svg" },
        { name: "turborepo", src: "/turborepo.svg" },
        { name: "prisma", src: "https://raw.githubusercontent.com/prisma/presskit/main/Assets/Prisma-DarkSymbol.svg" },
        { name: "postgresql", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original.svg" },
        { name: "supabase", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/supabase/supabase-original.svg" },
        { name: "razorpay", src: "/razorpay.svg" },
      ],
      imageLink: "/audient.png",
      liveLink: "https://audient.in/",
    },
    {
      name: "CVision",
      description: "CVision streamlines hiring by using advanced AI to analyze CVs and match candidates to job openings with precision. It offers intelligent CV parsing, detailed match scoring, and automated candidate ranking—empowering recruiters to make faster, smarter hiring decisions and helping job seekers find roles that truly fit.",
      date: "March 2025",
      techStack: [
        { name: "nextjs", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original.svg" },
        { name: "typescript", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/typescript/typescript-original.svg" },
        { name: "tailwindcss", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/tailwindcss/tailwindcss-original.svg" },
        { name: "turborepo", src: "/turborepo.svg" },
        { name: "prisma", src: "https://raw.githubusercontent.com/prisma/presskit/main/Assets/Prisma-DarkSymbol.svg" },
        { name: "postgresql", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original.svg" },
      ],
      liveLink: "https://cvision.vercel.app/",
      githubLink: "https://github.com/ayushk-1801/cvision",
      videoLink: "/cvision.mp4",
    },
    {
      name: "RE-DACT",
      description: "RE-DACT is a privacy-first web tool that automatically detects and redacts sensitive information like names, addresses, and phone numbers from documents. It offers a seamless user experience for uploading files, applying redactions, and securely downloading sanitized content—ensuring confidentiality and compliance.",
      date: "December 2024",
      techStack: [
        { name: "typescript", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/typescript/typescript-original.svg" },
        { name: "nextjs", src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original.svg" },
        { name: "tailwindcss", src: "https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/tailwindcss/tailwindcss-original.svg" },
      ],
      imageLink: "/redact.png",
      githubLink: "https://github.com/ayushk-1801/redact",
    }
  ],
};
